[package]
name = "lodestone_news"
version = "0.1.0"
authors = ["Kyle Clemens <jkc.clemens@gmail.com>"]

[dependencies]
hyper = "0.11"
hyper-rustls = "0.11"
make_hyper_great_again = "0.11"
serde = "1.0"
serde_json = "1.0"
dotenv = "0.10"
chrono = "0.4"
scraper = "0.4"
diesel = { version = "0.16", features = ["sqlite", "chrono"] }
diesel_codegen = { version = "0.16", features = ["sqlite"] }
error-chain = "0.11"
log = "0.3"
fern = "0.4"
ansi_term = "0.10"
ctrlc = "3.0"
chan = "0.1"
chan-signal = "0.3"
bus = "1.3"
